# Generated by Django 3.0.8 on 2020-08-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Zatuar Beneficios',
            },
        ),
        migrations.CreateModel(
            name='Contacto_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('mapa', models.TextField(blank=True, max_length=500, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('horario', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('horariosb', models.CharField(blank=True, default=1, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Contacto Empresa',
            },
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('principal', models.BooleanField(default=False)),
                ('img', models.FileField(blank=True, null=True, upload_to='descarga')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='descarga')),
            ],
            options={
                'verbose_name_plural': '9. Descarga',
            },
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='detalles')),
                ('image2', models.FileField(blank=True, null=True, upload_to='detalles')),
                ('image3', models.FileField(blank=True, null=True, upload_to='detalles')),
            ],
            options={
                'verbose_name_plural': '8. Detalles',
            },
        ),
        migrations.CreateModel(
            name='Galeria_Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '7. Galeria_Proceso',
            },
        ),
        migrations.CreateModel(
            name='Identidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Zatuar es',
            },
        ),
        migrations.CreateModel(
            name='Personalizaion_Poducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='producto')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Perzonalizacion de Productos',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('img1', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti1', models.CharField(blank=True, max_length=30, null=True)),
                ('img2', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti2', models.CharField(blank=True, max_length=30, null=True)),
                ('img3', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti3', models.CharField(blank=True, max_length=30, null=True)),
                ('ti4', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Proceso',
            },
        ),
        migrations.CreateModel(
            name='Redes_sociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('behance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('slider', models.FileField(blank=True, help_text='1884x529', null=True, upload_to='slider')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
        migrations.CreateModel(
            name='Zatuar_marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('logo_blanco', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('logo_negro', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('imagen', models.FileField(blank=True, help_text='400x400', null=True, upload_to='empresa/logo/')),
                ('portada', models.FileField(blank=True, help_text='1280x400', null=True, upload_to='empresa/logo/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Zatuar Marca',
            },
        ),
    ]
