# Generated by Django 3.0.9 on 2022-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zatuar_marca',
            name='imagen_2',
            field=models.FileField(blank=True, help_text='400x400', null=True, upload_to='empresa/logo/'),
        ),
    ]
