# Generated by Django 3.0.8 on 2020-08-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amarillo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='azul',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gris',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='naranja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='plomo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='verde',
            field=models.BooleanField(default=False),
        ),
    ]
