# Generated by Django 3.0.8 on 2020-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20200813_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rojo',
            field=models.BooleanField(default=False),
        ),
    ]
