# Generated by Django 3.0.8 on 2020-08-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_product_rojo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tamanos',
        ),
        migrations.AddField(
            model_name='product',
            name='tala_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tala_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tala_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tala_xl',
            field=models.BooleanField(default=False),
        ),
    ]
