# Generated by Django 3.0.8 on 2020-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_auto_20200813_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tamanio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
