# Generated by Django 3.0.8 on 2020-08-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_product_tamanio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
